title: NewRockWireless | Shop Smartphones, Tablets, Smart watches and more online
url: "https://50stateswireless-jpg.github.io"  # CHANGE THIS to your actual GitHub username
baseurl: "/50stateswirelessusa"                          # CHANGE THIS: leave empty if repo name matches, else "/repo-name"

# Enable Jekyll Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Standard Jekyll settings
markdown: kramdown
highlighter: rouge

